apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: project-pvc
  namespace: project
spec:
  storageClassName: local-storage
  accessModes:
   - ReadWriteOnce
  resources:
   requests:
    storage: 3Gi
