apiVersion: v1
kind: Service
metadata:
  name: project-service
  namespace: project
spec:
  selector:
    app: project
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 32000
